// nodesData.js
export const nodes = [
    {
        id: 1,
        mid: 6,
        fid: 5,
        pids: [2],
        name: 'Nguyễn Trần Lê',
        gender: 'male',
        photo: 'https://cdn.balkan.app/shared/9.jpg',
        born: '2001',
    },
    {
        id: 2,
        pids: [1],
        mid: 8,
        fid: 7,
        name: 'Nguyễn Thị Thu Hương',
        gender: 'female',
        photo: 'https://cdn.balkan.app/shared/w30/14.jpg',
    },
    {
        id: 4,
        mid: 1,
        fid: 2,
        name: 'Nguyễn Thị Minh Khai',
        gender: 'female',
        photo: 'https://cdn.balkan.app/shared/w10/4.jpg',
    },
    {
        id: 3,
        mid: 1,
        fid: 2,
        name: 'Nguyễn Văn Minh',
        gender: 'male',
        photo: 'https://cdn.balkan.app/shared/m10/1.jpg',
    },
    {
        id: 5,
        pids: [6],
        name: 'Trần Văn Bảo',
        gender: 'male',
        photo: 'https://cdn.balkan.app/shared/m60/1.jpg',
    },
    {
        id: 6,
        pids: [5],
        name: 'Lê Thị Hồng',
        gender: 'female',
        photo: 'https://cdn.balkan.app/shared/w60/1.jpg',
    },
    {
        id: 7,
        pids: [8],
        name: 'Trần Quốc Toản',
        gender: 'male',
        photo: 'https://cdn.balkan.app/shared/m60/2.jpg',
    },
    {
        id: 8,
        pids: [7],
        name: 'Nguyễn Thị Lan',
        gender: 'female',
        photo: 'https://cdn.balkan.app/shared/w60/2.jpg',
    },
];
